### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by datatraders** [datatraders/mysql-events#1]
```
/srv/node/smartsite/node_modules/mysql-events/index.js:20
                        newInst.child.on('child', child => newInst.emit('child', child));
                                                  ^

RangeError: Maximum call stack size exceeded
    at ZongJi.<anonymous> (/srv/node/smartsite/node_modules/mysql-events/index.js:20:51)
    at emitOne (events.js:77:13)
    at ZongJi.emit (events.js:169:7)
    at ZongJi.<anonymous> (/srv/node/smartsite/node_modules/mysql-events/index.js:20:68)
    at emitOne (events.js:77:13)
    at ZongJi.emit (events.js:169:7)
    at ZongJi.<anonymous> (/srv/node/smartsite/node_modules/mysql-events/index.js:20:68)
    at emitOne (events.js:77:13)
    at ZongJi.emit (events.js:169:7)
    at ZongJi.<anonymous> (/srv/node/smartsite/node_modules/mysql-events/index.js:20:68)
```

**Comment by datatraders** [comment]
we have written a new patch. it prevent the recursive error.
